services:
  stream-frontend:
    build:
      target: development
    image: stream-frontend-development
    container_name: stream-frontend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - stream-frontend

networks:
  stream-frontend:
    driver: bridge
    name: stream-frontend
