services:
  stream-frontend:
    extends:
      file: docker-compose.yaml
      service: stream-frontend
    build:
      target: development
    image: stream-frontend-test
    container_name: stream-frontend-test
    command: npm run test
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
