services:
  stream-frontend:
    extends:
      file: docker-compose.test.yaml
      service: stream-frontend
    command: npm run test:watch
    volumes:
      - ./.git:/home/node/.git
      - ./src:/home/node/src
